### ISSUE TITLE
Update ? 

### ISSUE THREAD

**Issue by MoMe36** [AlexLemminG/Rigify-To-Unity#1]
Hey ! Thanks for the implementation ! Very nice work. However, I had some troubles in Unity when exporting,  in particular with the hierarchy. I wrote some further lines as a patch [here](https://github.com/MoMe36/BlenderWorkflowAddons). 

Thanks !

**Comment by AlexLemminG** [comment]
Hi, what kind of troubles you have? I don't like idea of mixing def and org bones in hierarchy. And prefer to export deform bones only

**Comment by fkkcloud** [comment]
@AlexLemminG I think it does not show the "Prepare rig for unity" button for 2.8.1. Would it be a easy fix if I want to use it?
