### ISSUE TITLE
I think it does not show the "Prepare rig for unity" button for 2.8.1. Would it be a easy fix if I want to use it?

### ISSUE THREAD

**Issue by fkkcloud** [AlexLemminG/Rigify-To-Unity#2]
I think it does not show the "Prepare rig for unity" button for 2.8.1. Would it be an easy fix if I want to use it?

**Comment by AlexLemminG** [comment]
that's strange, I don't have any issues with latest blender version

**Comment by fkkcloud** [comment]
I think it works for non-legacy rigs but for legacy it supposes to not work? For now, I modified the very original "Rigify" script to work with 2.8.1 by removing the 'try' on poll() to have the UI appear and also minor fix on fbx export since API seems to be changed on "select". it seems to work at least for my purposes. Yeah but Im not sure. (not super familiar with Blender yet ;) anyway thanks! https://github.com/fkkcloud/rigify4mechanim_blender2.8.1/blob/master/Rigify4Mecanim_Blender281.py

**Comment by WilledgeR** [comment]
it's not showing in 2.90

**Comment by AlexLemminG** [comment]
> 
> 
> it's not showing in 2.90

Works for me. At least for steam version of blender

**Comment by downislanda** [comment]
maybe im doing something wrong here but im following this tutorial to the "T" i enabled the add-on in the preferences menu, it showed up perfectly fine, i hit enable, closed the window but the "rigify to unity convertor" wont show up in the object data properties tab.. ive tried refreshing, restarting, deleting re-installing.. im using blender 2.90.1 please help, my emails downislanda@hotmail.com 
![Untitled](https://user-images.githubusercontent.com/74220929/100194976-7c9ecf80-2eab-11eb-8395-83d50e5ff077.png)

**Comment by downislanda** [comment]
nevermind i used the persons script up above and it immediately popped up but thank you for the script its deff gonna come in handy

**Comment by AlexLemminG** [comment]
> 
> 
> maybe im doing something wrong here but im following this tutorial to the "T" i enabled the add-on in the preferences menu, it showed up perfectly fine, i hit enable, closed the window but the "rigify to unity convertor" wont show up in the object data properties tab.. ive tried refreshing, restarting, deleting re-installing.. im using blender 2.90.1 please help, my emails [downislanda@hotmail.com](mailto:downislanda@hotmail.com)
> ![Untitled](https://user-images.githubusercontent.com/74220929/100194976-7c9ecf80-2eab-11eb-8395-83d50e5ff077.png)

You need to generate rig using rigify first. Then button will show up.
![1](https://user-images.githubusercontent.com/3332929/100215669-58320a00-2f22-11eb-91f5-5984a3697d3f.png)
![2](https://user-images.githubusercontent.com/3332929/100215673-59fbcd80-2f22-11eb-90d7-50a0a1f94488.png)

**Comment by downislanda** [comment]
Well the model i was Using already had a rig, do I generate a rig still, then when the converter shows up I can use it for the model that had the rig on it already

Sent via the Samsung Galaxy S20 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by AlexLemminG** [comment]
I'm not sure if existing rig is the right one to use. "Generate rig" button is actually riggify function to generate actual rig from metarig. So I can only assume that rig is not fully created yet

**Comment by downislanda** [comment]
I see ok ill give it a try and see what happens then thank u

Sent via the Samsung Galaxy S20 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by downislanda** [comment]
ok ill give it a go, the rig on this model is a rigify rig, the head bone looks a bit different but ill try on another model n see

________________________________

**Comment by MPagliari** [comment]
Yeah I came here with the same issue.
I am using a basic human Meta rig on blender 2.90.1 I am new to this so not ruling out that I'm doing it wrong though.
![blender](https://user-images.githubusercontent.com/1887228/101333671-cbb31000-386e-11eb-9de9-62fd5a200b16.PNG)

**Comment by downislanda** [comment]
Well I've been doing a work around instead seems to be working, unity accepts blend files so I just put the file right into my assets folder

Sent via the Samsung Galaxy S20 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by AlexLemminG** [comment]
@MPagliari it should be inside "rig" object. Does it appear there?

**Comment by c006** [comment]
A suggestion would be to add to the instructions, the rig arrows on the floor must be selected for the plugin show up.
I spent an hour+ going back and forth trying to figure it out, pretty subtle.

Not showing:
![screencapture_blender](https://user-images.githubusercontent.com/7686064/106349925-ce3a5080-6286-11eb-89ee-0efcaea365a2.jpg)

Showing when selected:
![screencapture_blender2](https://user-images.githubusercontent.com/7686064/106349932-e27e4d80-6286-11eb-8e53-b0be1fb06141.jpg)

**Comment by AlexLemminG** [comment]
@c006 thanks for suggestion, added it to readme
