### ISSUE TITLE
"rubber" deformation in rigify rig

### ISSUE THREAD

**Issue by Buckaroo292** [AlexLemminG/Rigify-To-Unity#4]
The removal of "unnecessary" bones causes false deformations of body parts.
Maybe not all bones should be deleted. Renaming is fine, so that the armature in Unity is correctly assigned as "humanoid".
Before:
![grafik](https://user-images.githubusercontent.com/61068788/87514020-e398b600-c679-11ea-808d-71957915580d.png)
After:
![grafik](https://user-images.githubusercontent.com/61068788/87514061-f4e1c280-c679-11ea-96b9-19c64e947487.png)

**Comment by AlexLemminG** [comment]
Without deleting some arm bones and extending the others, rig looks odd in Unity. I'm not sure Unity fully understands such bones. 
![изображение](https://user-images.githubusercontent.com/3332929/87855668-6e034300-c922-11ea-978f-194c4aad6ba9.png)

**Comment by AlexLemminG** [comment]
disabeld removing in this branch
https://github.com/AlexLemminG/Rigify-To-Unity/tree/non-basic-Human
