### ISSUE TITLE
Fingers get ignored

### ISSUE THREAD

**Issue by iceandstorm** [AlexLemminG/Rigify-To-Unity#5]
Hi,
we have a problem that fingers from the rig are ignored in general. In the new generated rig all finger bones are gone.

We follow these naming conventions from the unity mecanim manual site. 

Any steps we need to follow to prevent this?

**Comment by AlexLemminG** [comment]
Added support for finger bones here
https://github.com/AlexLemminG/Rigify-To-Unity/tree/non-basic-Human
Basic idea is having them parented to hand bone,

**Comment by AlexLemminG** [comment]
Some expected namings could be found in this script
https://github.com/Unity-Technologies/UnityCsReference/blob/master/Editor/Mono/Inspector/Avatar/AvatarAutoMapper.cs
