### ISSUE TITLE
No fingers nor Face?

### ISSUE THREAD

**Issue by giantkiller** [AlexLemminG/Rigify-To-Unity#6]
I used this and then the rig in Unity has no fingers nor face bones?
How is anybody getting rigs into Unity without using Autocad products?
I use Blender for the switch because the fbxs vary so much as to make a direct import to Unity not working.
A lot of models were never meant to be imported to Unity but we still try.

**Comment by AlexLemminG** [comment]
no, unfortunately fingers and face bones are not supported
