### ISSUE TITLE
Not Showing The Addon Options

### ISSUE THREAD

**Issue by gaybeeeee** [AlexLemminG/Rigify-To-Unity#9]
Why doesnt the blender 3.0 show the options of addon? There is no Rigify To Unity Converter. Please what can I do, I'm really loosing my mind with this.

**Comment by AlexLemminG** [comment]
Please make sure you are using 'Basic Human (Meta-Rig)', 'Generate Rig' button is pressed and the 'rig' object is selected.
![изображение](https://user-images.githubusercontent.com/3332929/154932253-74cc032d-5c0c-4d93-9cd7-f04132931eae.png)
